version: '3'

services:
  user:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: user
    env_file: .env
    environment:
      - MONGO_DB_USER=$MONGO_DB_USER
      - MONGO_DB_PASSWORD=$MONGO_DB_PASSWORD
      - MONGO_DB_HOST=$MONGO_DB_HOST
      - MONGO_DB_PORT=$MONGO_DB_PORT
      - MONGO_DB_NAME=$MONGO_DB_NAME
      - PORT=$PORT
      - SECRET=$SECRET 
      - TOKEN_EXPIRATION=$TOKEN_EXPIRATION 

    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    networks:
      - app-network
    depends_on: 
      - mongo

  mongo:
    image: mongo:4.1.8-xenial
    container_name: mongo
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:     
      - dbdata:/data/db
    networks:
      - app-network

  # mongo-express:
  #   image: mongo-express
  #   environment:
  #     - ME_CONFIG_MONGODB_SERVER=mongo
  #     - ME_CONFIG_MONGODB_PORT=27017
  #     - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
  #     - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
  #     - ME_CONFIG_MONGODB_AUTH_USERNAME=root
  #     - ME_CONFIG_MONGODB_AUTH_PASSWORD=password
  #     - ME_CONFIG_BASICAUTH_USERNAME=dev
  #     - ME_CONFIG_BASICAUTH_PASSWORD=dev
  #   depends_on:
  #     - mongo
  #   ports:
  #     - "8888:8081"
  #   networks:
  #     - app-network    

networks:
  app-network:
    driver: bridge

volumes:
  dbdata: