version: '3'

services:
  user:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: user
    env_file: .env
    environment:
      - MONGO_DB_USER=$MONGO_DB_USER
      - MONGO_DB_PASSWORD=$MONGO_DB_PASSWORD
      - MONGO_DB_HOST=$MONGO_DB_HOST
      - MONGO_DB_PORT=$MONGO_DB_PORT
      - MONGO_DB_NAME=$MONGO_DB_NAME
      - PORT=$PORT 
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    networks:
      - app-network
    depends_on: 
      - mongo

  mongo:
    image: mongo:4.1.8-xenial
    container_name: mongo
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:     
      - dbdata:/data/db
    networks:
      - app-network  

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
  node_modules:  